apiVersion: v1
kind: DeploymentConfig
metadata:
  name: basic-go-nov-2020-960028
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: basic-go-nov-2020-960028
    spec:
      containers:
      - name: basic-go-nov-2020-960028
        ports:
          - name: api
            containerPort: 8080
            protocol: TCP
        image: basic-go-nov-2020-image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /.cache
            name: cache
      imagePullSecrets:
        - name: academy-artifactory
      volumes:
        - name: cache
          emptyDir: {}